//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PpeRequestGenTestTool.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PpeRequestGenTestTool.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first_name
        ///Aarika
        ///Abba
        ///Abbe
        ///Abbey
        ///Abbie
        ///Abby
        ///Abbye
        ///Abdel
        ///Abel
        ///Abelard
        ///Abey
        ///Abigael
        ///Abigail
        ///Abraham
        ///Ad
        ///Ada
        ///Adan
        ///Adara
        ///Addi
        ///Addie
        ///Addison
        ///Addy
        ///Adelaida
        ///Adelaide
        ///Adelbert
        ///Adeline
        ///Adey
        ///Adolf
        ///Adolpho
        ///Adria
        ///Adrian
        ///Adriane
        ///Adrianna
        ///Adriano
        ///Adrien
        ///Adrienne
        ///Aeriela
        ///Afton
        ///Agatha
        ///Agathe
        ///Agnella
        ///Agnes
        ///Agnese
        ///Agneta
        ///Agosto
        ///Aguie
        ///Aidan
        ///Aigneis
        ///Aila
        ///Aile
        ///Ailina
        ///Ainslee
        ///Ainsley
        ///Aksel
        ///Al
        ///Alaine
        ///Alair
        ///Alana
        ///Alanah
        ///Aland
        ///Alanson
        ///Alard
        ///Alasteir
        ///Albert
        ///Albertine
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string first_names {
            get {
                return ResourceManager.GetString("first_names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last_names
        ///Abbatt
        ///Abbitt
        ///Abden
        ///Abdey
        ///Abdon
        ///Abella
        ///Ablett
        ///Ablitt
        ///Abotson
        ///Abrahim
        ///Abrahm
        ///Abrahmovici
        ///Abrami
        ///Abramovic
        ///Abramovitz
        ///Accum
        ///Acors
        ///Adami
        ///Adamiak
        ///Adamides
        ///Adamik
        ///Adamsen
        ///Adamski
        ///Adamsky
        ///Adamsson
        ///Adanet
        ///Addionizio
        ///Adicot
        ///Adiscot
        ///Adnams
        ///Adolfsen
        ///Adriaan
        ///Agates
        ///Aiers
        ///Aimeric
        ///Airy
        ///Aizlewood
        ///Akast
        ///Akeherst
        ///Akrigg
        ///Albion
        ///Albiston
        ///Albrook
        ///Albutt
        ///Alcoran
        ///Aldin
        ///Alenov
        ///Alessandone
        ///Aleveque
        ///Alexsandrev
        ///Algore
        ///Allain
        ///Allan
        ///Allaway
        ///Allbones
        ///Allder
        ///Alleburto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string last_names {
            get {
                return ResourceManager.GetString("last_names", resourceCulture);
            }
        }
    }
}
